// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateDiagramReducer from "../create_diagram_reducer";
import CreateFolderReducer from "../create_folder_reducer";
import DeleteDiagramReducer from "../delete_diagram_reducer";
import DeleteFolderReducer from "../delete_folder_reducer";
import SetNameReducer from "../set_name_reducer";
import ShareFolderReducer from "../share_folder_reducer";
import UnshareFolderReducer from "../unshare_folder_reducer";
import UpdateDiagramXmlReducer from "../update_diagram_xml_reducer";

export type CreateDiagramParams = __Infer<typeof CreateDiagramReducer>;
export type CreateFolderParams = __Infer<typeof CreateFolderReducer>;
export type DeleteDiagramParams = __Infer<typeof DeleteDiagramReducer>;
export type DeleteFolderParams = __Infer<typeof DeleteFolderReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type ShareFolderParams = __Infer<typeof ShareFolderReducer>;
export type UnshareFolderParams = __Infer<typeof UnshareFolderReducer>;
export type UpdateDiagramXmlParams = __Infer<typeof UpdateDiagramXmlReducer>;

