// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Diagram = __t.object("Diagram", {
  id: __t.u64(),
  folderId: __t.u64(),
  name: __t.string(),
  xmlContent: __t.string(),
  ownerIdentity: __t.identity(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Diagram = __Infer<typeof Diagram>;

export const DiagramLock = __t.object("DiagramLock", {
  id: __t.u64(),
  diagramId: __t.u64(),
  lockedBy: __t.identity(),
  lockedAt: __t.timestamp(),
});
export type DiagramLock = __Infer<typeof DiagramLock>;

export const Folder = __t.object("Folder", {
  id: __t.u64(),
  name: __t.string(),
  ownerIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Folder = __Infer<typeof Folder>;

export const FolderShare = __t.object("FolderShare", {
  id: __t.u64(),
  folderId: __t.u64(),
  sharedWithIdentity: __t.identity(),
  permission: __t.string(),
  createdAt: __t.timestamp(),
});
export type FolderShare = __Infer<typeof FolderShare>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  email: __t.string(),
  online: __t.bool(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

