// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateDiagramReducer from "../create_diagram_reducer";
import CreateFolderReducer from "../create_folder_reducer";
import DeleteDiagramReducer from "../delete_diagram_reducer";
import DeleteFolderReducer from "../delete_folder_reducer";
import LockDiagramReducer from "../lock_diagram_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RenameDiagramReducer from "../rename_diagram_reducer";
import RenameFolderReducer from "../rename_folder_reducer";
import ShareFolderReducer from "../share_folder_reducer";
import UnlockDiagramReducer from "../unlock_diagram_reducer";
import UnshareFolderReducer from "../unshare_folder_reducer";
import UpdateDiagramReducer from "../update_diagram_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type CreateDiagramParams = __Infer<typeof CreateDiagramReducer>;
export type CreateFolderParams = __Infer<typeof CreateFolderReducer>;
export type DeleteDiagramParams = __Infer<typeof DeleteDiagramReducer>;
export type DeleteFolderParams = __Infer<typeof DeleteFolderReducer>;
export type LockDiagramParams = __Infer<typeof LockDiagramReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RenameDiagramParams = __Infer<typeof RenameDiagramReducer>;
export type RenameFolderParams = __Infer<typeof RenameFolderReducer>;
export type ShareFolderParams = __Infer<typeof ShareFolderReducer>;
export type UnlockDiagramParams = __Infer<typeof UnlockDiagramReducer>;
export type UnshareFolderParams = __Infer<typeof UnshareFolderReducer>;
export type UpdateDiagramParams = __Infer<typeof UpdateDiagramReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

